import MarketSelector from "@/components/markets/MarketSelector";
import Image from "next/image";
import Link from "next/link";
import { ArrowUp, Instagram, Linkedin } from "lucide-react";
const columns = [
  { title: "Explore", links: [["The Alutta way", "#about"], ["Destinations", "#destinations"], ["Your journey", "#how-it-works"], ["Questions", "#questions"]] },
  { title: "Company", links: [["About us", "#about"], ["Careers", "/careers"], ["Join the waitlist", "/waitlist"], ["Contact", "mailto:hello@alutta.com"]] },
  { title: "Legal", links: [["Privacy", "/privacy"], ["Terms", "/terms"]] },
];
export default function CareersFooter({ topId = "careers-heading", nigeria = false }: { topId?: string; nigeria?: boolean }){return     <footer className="closing-footer"><div className="closing-footer-inner"><div className="closing-footer-grid"><div className="closing-brand"><Link href={nigeria ? "/ng" : "/"} aria-label="Alutta home"><Image src="/brand/logo-horizontal-coloured.svg" alt="Alutta" width={132} height={39} /></Link><p>A brighter you, anywhere.</p><p>We help you study, pay, travel and settle abroad in one place.</p><div className="closing-socials"><a href="https://linkedin.com/company/alutta" target="_blank" rel="noopener noreferrer" aria-label="Alutta on LinkedIn"><Linkedin size={17} /></a><a href="https://twitter.com/aluttahq" target="_blank" rel="noopener noreferrer" aria-label="Alutta on X"><svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true"><path d="M4 3h4l12 18h-4L4 3Zm16 0L4 21" fill="none" stroke="currentColor" strokeWidth="1.6" /></svg></a><a href="https://instagram.com/aluttahq" target="_blank" rel="noopener noreferrer" aria-label="Alutta on Instagram"><Instagram size={17} /></a></div></div>{columns.map(column => <nav key={column.title} aria-label={`${column.title} footer links`}><h3>{column.title}</h3>{column.links.map(([label, href]) => <Link key={label} href={nigeria && href === "/waitlist" ? "/ng/waitlist" : href.startsWith("#") ? nigeria ? `/ng${href === "#destinations" ? "#profile" : href}` : `/${href}` : href}>{label}</Link>)}</nav>)}<div className="closing-globe" aria-hidden="true"><span>More stories<br />across borders.</span><Image className="closing-world-map" src="/images/footer-world-map.svg" alt="" width={660} height={400} /></div></div><div className="market-footer"><MarketSelector /></div><div className="closing-footer-bottom"><span>© {new Date().getFullYear()} Alutta Inc. All rights reserved.</span><div><span>Students today. A brighter tomorrow.</span><a href={`#${topId}`} aria-label="Back to top"><ArrowUp size={18} /></a></div></div><p className="closing-legal-note">Alutta is not a bank. Payment services are provided through licensed partners. Admission and visa decisions rest with universities and the relevant authorities.</p></div></footer>;}
