"use client";

import Image from "next/image";
import { useState } from "react";
import { ArrowLeft, ArrowRight, MapPin } from "lucide-react";
import type { Showcase } from "@/lib/showcase";

const places = [
  { name: "United States", code: "us", short: "the USA", flag: "🇺🇸", location: "New York, United States", image: "usa", title: "Big ambitions. A world of possibilities.", description: "Find your campus, explore your interests, and build connections in a country full of different experiences.", highlights: ["Campus life", "Broad study options", "Global connections"], schools: ["Harvard University", "Stanford University", "New York University"] },
  { name: "United Kingdom", code: "gb", short: "the UK", flag: "🇬🇧", location: "London, United Kingdom", image: "uk", title: "World-class education and global opportunities.", description: "Explore leading universities, join a diverse community, and find a new perspective on your future.", highlights: ["Historic campuses", "Global connections", "Diverse communities"], schools: ["University of Oxford", "University of Manchester", "University of Edinburgh"] },
  { name: "Canada", code: "ca", short: "Canada", flag: "🇨🇦", location: "Toronto, Canada", image: "canada", title: "Fresh perspectives. A future with room to grow.", description: "Discover vibrant cities, welcoming campuses, and new possibilities for your next chapter.", highlights: ["Vibrant cities", "Inspiring campuses", "New perspectives"], schools: ["University of Toronto", "McGill University", "University of British Columbia"] },
  { name: "China", short: "China", code: "cn", location: "Shanghai, China", image: "china", title: "New perspectives. Extraordinary possibilities.", description: "Discover dynamic cities, explore rich traditions, and find your next chapter in a new learning environment.", highlights: ["Dynamic cities", "Rich traditions", "New connections"], schools: ["Tsinghua University", "Peking University", "Fudan University"] },
  { name: "Australia", code: "au", short: "Australia", flag: "🇦🇺", location: "Sydney, Australia", image: "australia", title: "A brighter outlook. A whole new horizon.", description: "Explore lively student cities, discover new ways to learn, and make space for the adventure ahead.", highlights: ["Student cities", "Fresh horizons", "Connected campuses"], schools: ["University of Melbourne", "University of Sydney", "Monash University"] },
];

export default function DestinationShowcase({ onExplore, showcase }: { onExplore: (code: string) => void; showcase: Showcase }) {
  const [selected, setSelected] = useState(0);
  const [showSchools, setShowSchools] = useState(false);
  const place = places[selected];
  // What the catalogue lists for this country today. When it lists nothing,
  // the panel shows well-known universities and says exactly that, so a name
  // on this page is never read as a partnership that does not exist.
  const listed = showcase.schools.filter((school) => school.countryCode === place.code.toUpperCase()).slice(0, 6);
  function choose(index: number) { setSelected(index); setShowSchools(false); }
  return <section className="destination-showcase" id="destinations" aria-labelledby="destination-title">
    <div className="destination-heading"><div><h2 id="destination-title">Where to next?</h2><p>Discover top study destinations and find the right fit for your goals.</p></div><p className="destination-intro">A new perspective, new opportunities and a brighter you. Explore where you could belong.</p></div>
    <div className="destination-controls"><div className="destination-options" role="tablist" aria-label="Study destinations">{places.map((item,index) => <button key={item.name} id={`destination-option-${index}`} role="tab" aria-selected={selected === index} aria-controls="destination-panel" tabIndex={selected === index ? 0 : -1} onClick={() => choose(index)} onKeyDown={event => { if (['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) { event.preventDefault(); const next = event.key === 'Home' ? 0 : event.key === 'End' ? places.length - 1 : (selected + (event.key === 'ArrowRight' ? 1 : places.length - 1)) % places.length; choose(next); document.getElementById(`destination-option-${next}`)?.focus(); } }}><Image className="destination-flag" src={`/images/flag-${item.code}.svg`} alt="" width={29} height={20} />{item.name}<ArrowRight size={18} /></button>)}</div><div className="destination-arrows"><button aria-label="Previous destination" disabled={selected === 0} onClick={() => choose(selected - 1)}><ArrowLeft /></button><button aria-label="Next destination" disabled={selected === places.length - 1} onClick={() => choose(selected + 1)}><ArrowRight /></button></div></div>
    <div className="destination-panel" id="destination-panel" role="tabpanel" aria-labelledby={`destination-option-${selected}`}><div className="destination-photo" key={place.image}><Image src={`/images/destination-${place.image}.jpg`} alt={place.location} fill sizes="(max-width: 800px) 100vw, 48vw" /><span className="destination-location"><MapPin size={18} fill="currentColor" />{place.location}</span></div><div className="destination-content"><p className="destination-eyebrow">STUDY IN {place.name === 'United Kingdom' || place.name === 'United States' ? 'THE ' : ''}{place.name.toUpperCase()}</p><h3>{place.title}</h3><p className="destination-description">{place.description}</p><div className="destination-highlights">{place.highlights.map((label,index) => <div key={label}><span>0{index + 1}</span><strong>{label}</strong></div>)}</div><div className="destination-actions"><button className="atlas-button" onClick={() => onExplore(place.code)}>Explore {place.short}<ArrowRight size={19} /></button><button className="destination-secondary" aria-expanded={showSchools} aria-controls="destination-schools" onClick={() => setShowSchools(!showSchools)}>{showSchools ? 'Hide universities' : 'View universities'}</button></div>{showSchools && <div className="destination-schools" id="destination-schools">{listed.length > 0 ? <><p>On Alutta today</p>{listed.map(school => <span key={school.name}>{school.name}</span>)}</> : <><p>Well-known universities in {place.short}. Partnerships on Alutta are announced as they are confirmed.</p>{place.schools.map(school => <span key={school}>{school}</span>)}</>}</div>}</div></div>
  </section>;
}
