import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, ArrowRight, FileCheck2, GraduationCap, Globe2, Layers3, Route, UserRound, Check } from "lucide-react";
import { ScrollProfile, ProgrammeRibbon, NigeriaFlightMap } from "@/components/home/NigeriaMotion";
import HomeHeader from "@/components/home/HomeHeader";
import CareersFooter from "@/components/home/CareersFooter";
import { fetchShowcase } from "@/lib/showcase";
import "@/components/home/home.css";
import "./nigeria.css";
export const metadata: Metadata = {title:"Alutta Nigeria | One profile. More possibilities.", description:"A clearer path to postgraduate study in Nigeria and beyond. Join the waitlist for a reusable Alutta profile and applications to participating institutions.", alternates:{canonical:"/ng",languages:{"en-NG":"/ng",en:"/","x-default":"/"}}};
const steps=[{Icon:UserRound,title:"Build your profile once.",text:"Bring your academic background, interests, and documents together in one place."},{Icon:GraduationCap,title:"Find your next programme.",text:"Discover master’s and PhD opportunities at participating institutions as they join Alutta."},{Icon:FileCheck2,title:"Apply with less repetition.",text:"Reuse your profile, then complete the requirements specific to each programme."},{Icon:Route,title:"Keep every next step in view.",text:"Stay on top of application progress, outstanding documents, and what comes next."}];
const faqs=[["Is Alutta Nigeria available yet?","We’re building this experience and inviting students to join the waitlist. We’ll share updates as participating institutions and application capabilities become available."],["Can I apply to every university in Nigeria?","Applications through Alutta are planned for participating institutions. We’ll publish available institutions and programmes as partnerships are confirmed."],["Will one profile cover everything?","Yes. One Alutta profile is at the heart of our vision: use it to apply to all participating institutions, in Nigeria and globally. Build your academic story once and reuse it for each application, adding any programme-specific requirements along the way."],["Can I use my profile for schools abroad?","That’s the vision: one Alutta profile for participating opportunities in Nigeria and globally. Availability will depend on the institutions and programmes supported at launch."],["Does choosing Nigeria restrict my study destination?","No. Your website region is separate from your study destination. You can explore opportunities at home and abroad, and switch to the Global website whenever you like."],["Is it free to join the waitlist?","Yes. Joining the waitlist is free. Application fees and any paid services will be explained separately when those options become available."]];
export default async function NigeriaPage(){
// Institutions the catalogue lists in Nigeria, read at render time. The
// section renders only when there is something to show; until then the copy
// above says partnerships are announced as they are confirmed, and that stays true.
const showcase = await fetchShowcase({ countries: ["NG"] });
return <div className="atlas-home ng-home"><HomeHeader/>
<section className="ng-hero ng-container"><div><span className="ng-eyebrow"><Image src="/images/flag-ng.svg" alt="" width={25} height={17}/> ALUTTA NIGERIA</span><h1 id="ng-heading">One profile.<br/>More possibilities.<br/><em>Your next degree.</em></h1><p>A master’s in Nigeria. A PhD beyond borders. We’re building a simpler way to take your next academic step—with one profile for participating institutions, at home and abroad.</p><div className="ng-actions"><Link className="atlas-button" href="/ng/waitlist">Join the waitlist <ArrowUpRight size={20}/></Link><a href="#how-it-works">See how it works <ArrowRight size={18}/></a></div><span className="ng-small">Built for your ambition. Starting with Nigeria.</span></div><div className="ng-hero-visual"><div className="ng-photo"><Image src="/images/lagos-students.png" alt="Illustration of Nigerian postgraduate students by the Lagos waterfront and Lekki-Ikoyi bridge" fill priority sizes="(max-width:800px) 90vw,50vw"/></div><span className="ng-sticker">YOUR AMBITION<br/>BELONGS HERE <ArrowUpRight size={25}/></span><div className="ng-profile-label"><span><UserRound size={23}/></span><div>Your Alutta profile<strong>One start. Many next steps.</strong></div></div></div></section>
<ProgrammeRibbon/>
<section className="ng-purpose ng-container" id="about"><h2>Your ambition is big.<br/><em>The process shouldn’t<br/>get in the way.</em></h2><div><p>The same details. Another portal. One more document to upload. Applying for your next degree can feel like starting over, every time.</p><p>Alutta brings the journey together. A reusable academic profile, participating programmes to explore, and a clearer view of your applications—so you can focus on where you want to go.</p><Link href="/ng/waitlist">Be part of what’s next <ArrowUpRight size={19}/></Link></div></section>
<section className="ng-profile-section" id="profile"><div className="ng-container ng-profile-grid"><div><span className="ng-eyebrow">LESS STARTING OVER. MORE MOVING FORWARD.</span><h2>Everything that<br/>makes you, <em>you.</em><br/>In one profile.</h2><p>Your academic story deserves more than a folder full of forms. Bring it together once, and build on it as your ambitions grow.</p><ul>{['Academic background and qualifications','Research interests and study goals','Documents, ready for the next step'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></div><ScrollProfile><div className="ng-preview-top"><span><UserRound size={28}/></span><div><small>YOUR ACADEMIC STORY</small><h3>Ready for what’s next.</h3></div><Globe2 size={23}/></div>{[[GraduationCap,'Your education','Qualifications, experience, and achievements'],[Layers3,'Your interests','The questions you want to explore'],[FileCheck2,'Your documents','A home for your academic essentials']].map(([Icon,title,detail])=>{const I=Icon as typeof GraduationCap;return <div className="ng-preview-row" key={String(title)}><I size={21}/><div><strong>{String(title)}</strong><p>{String(detail)}</p></div><Check size={17}/></div>})}<div className="ng-preview-footer">One profile. Opportunities in more places. <ArrowUpRight size={19}/></div></ScrollProfile></div></section>
<section className="ng-steps ng-container" id="how-it-works"><div className="ng-section-heading"><h2>Your next chapter.<br/><em>A clearer way there.</em></h2><p>The experience we’re building, from your first profile to your next application.</p></div><ol>{steps.map(({Icon,title,text},i)=><li key={title}><div><Icon size={27}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
{showcase.schools.length > 0 && <section className="ng-partners ng-container" id="institutions" aria-labelledby="ng-partners-heading"><div className="ng-section-heading"><div><span className="ng-eyebrow">PARTICIPATING INSTITUTIONS</span><h2 id="ng-partners-heading">Already on Alutta.<br/><em>More on the way.</em></h2></div><p>Institutions and programmes you can find on Alutta Nigeria today.</p></div><ul className="ng-partner-list">{showcase.schools.map(school=><li key={school.name}><strong>{school.name}</strong><span>{[school.city, school.levels.join(" · ")].filter(Boolean).join(" · ")}</span><p>{school.programmes.join(", ")}</p>{school.aluttaSubmits && <small>Apply through Alutta</small>}</li>)}</ul></section>}
<section className="ng-global ng-container" id="global-journey"><div><span className="ng-eyebrow">ROOTED HERE. OPEN TO THE WORLD.</span><h2>Start here.<br/><em>Go anywhere.</em></h2><p>Your ambitions don’t stop at a border. Explore the global Alutta experience for your study abroad journey, with the same account and a wider world of possibilities.</p><Link className="atlas-button lime" href="/">Explore Alutta Global <Globe2 size={20}/></Link></div><NigeriaFlightMap/></section>
<section className="ng-faq ng-container" id="questions"><div><span className="ng-eyebrow">A LITTLE MORE CLARITY</span><h2>Big plans.<br/><em>Good questions.</em></h2><p>Here’s what to know about Alutta Nigeria.</p></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section className="ng-final ng-container"><span className="ng-eyebrow">YOUR NEXT CHAPTER STARTS WITH ONE STEP</span><h2>Bring your ambition.<br/><em>We’ll build the path.</em></h2><p>Join the Nigeria waitlist for updates on the experience we’re building.</p><Link className="atlas-button" href="/ng/waitlist">Save your place <ArrowUpRight size={20}/></Link></section><CareersFooter nigeria topId="ng-heading"/></div>}
